version: '3.8'

services:
  web:
    image: ctulhufromrlieh/hwg4c-web:latest
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django-data/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    expose:
     - "5432" 
    ports:
     - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_USER:hello_django
      - POSTGRES_DB:hello_django_dev
      - POSTGRES_PASSWORD:hello_django
  nginx:
    image: ctulhufromrlieh/hwg4c-nginx:latest
    ports:
      - 80:80

# volumes:
#   postgres_data:
